interface EnvConfig {
  REDIRECT_URL: string;
  OPEN_WEATHER_API_KEY: string;
  OPEN_WEATHER_BASE_URL: string;
  NOAA_GOV_CURRENT_BASE_URL: string;
  OPEN_METEO_BASE_URL: string;
  OPEN_METEO_ARCHIVE_URL: string;
  WEATHER_UNITS: 'metric' | 'imperial';
  LATITUDE: number;
  LONGITUDE: number;
  BIRTH_DATE: string;
  SUPBASE_URL: string;
  SUPBASE_KEY: string;
  REACT_APP_APPWRITE_PROJECT_ID: string;
  SJCL_KEY_STRENGTH_FACTOR: number;
  SJCL_KEY_SIZE: number;
  SJCL_GENERATE_SALT_WORDS: number;
  SJCL_GENERATE_SALT_PARANOIA: number;
  NOAA_GOV_CURRENT_RESOURCE_URL: string;
  NOAA_GOV_CURRENT_RESOURCE_TITLE: string;
  OPEN_METEO_RESOURCE_URL: string;
  OPEN_METEO_RESOURCE_TITLE: string;
}

export const env: EnvConfig = {
  REDIRECT_URL: import.meta.env.VITE_REDIRECT_URL.trim(),
  OPEN_WEATHER_API_KEY: import.meta.env.VITE_OPEN_WEATHER_API_KEY,
  OPEN_WEATHER_BASE_URL: import.meta.env.VITE_OPEN_WEATHER_BASE_URL,
  NOAA_GOV_CURRENT_BASE_URL: import.meta.env.VITE_NOAA_GOV_CURRENT_BASE_URL,
  OPEN_METEO_BASE_URL: import.meta.env.VITE_OPEN_METEO_BASE_URL,
  WEATHER_UNITS: import.meta.env.VITE_WEATHER_UNITS as 'metric' | 'imperial',
  LATITUDE: Number.parseFloat(import.meta.env.VITE_LATITUDE) || 51.5074,
  LONGITUDE: Number.parseFloat(import.meta.env.VITE_LONGITUDE) || -0.1278,
  BIRTH_DATE: import.meta.env.VITE_BIRTH_DATE || '',
  SUPBASE_URL: import.meta.env.VITE_SUPBASE_URL || '',
  SUPBASE_KEY: import.meta.env.VITE_SUPBASE_KEY || '',
  REACT_APP_APPWRITE_PROJECT_ID: import.meta.env.VITE_REACT_APP_APPWRITE_PROJECT_ID || '',
  SJCL_KEY_STRENGTH_FACTOR: Number.parseInt(import.meta.env.VITE_SJCL_KEY_STRENGTH_FACTOR) || 10000,
  SJCL_KEY_SIZE: Number.parseInt(import.meta.env.VITE_SJCL_KEY_SIZE) || 256,
  SJCL_GENERATE_SALT_WORDS: Number.parseInt(import.meta.env.VITE_SJCL_GENERATE_SALT_WORDS) || 2,
  SJCL_GENERATE_SALT_PARANOIA:
    Number.parseInt(import.meta.env.VITE_SJCL_GENERATE_SALT_PARANOIA) || 0,
  NOAA_GOV_CURRENT_RESOURCE_URL: import.meta.env.VITE_NOAA_GOV_CURRENT_RESOURCE_URL || '',
  NOAA_GOV_CURRENT_RESOURCE_TITLE: import.meta.env.VITE_NOAA_GOV_CURRENT_RESOURCE_TITLE || '',
  OPEN_METEO_RESOURCE_URL: import.meta.env.VITE_OPEN_METEO_RESOURCE_URL || '',
  OPEN_METEO_RESOURCE_TITLE: import.meta.env.VITE_OPEN_METEO_RESOURCE_TITLE || '',
  OPEN_METEO_ARCHIVE_URL: import.meta.env.VITE_OPEN_METEO_ARCHIVE_RESOURCE_URL || '',
};
